services:
  db:
    container_name: db
    image: postgres
    restart: always
    user: postgres
    volumes:
      - kanban-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: -p 5432
    environment:
      - POSTGRES_DB=kanban
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 50
    networks:
      - kanban-network
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DEFAULT_PORT=5432
    networks:
      - kanban-network
  app:
    container_name: kanban-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kanban-network

volumes:
  kanban-db-data:
networks:
  kanban-network:
    driver: bridge